language: ruby
rvm:
  - 2.4.2
services:
  - mysql
  - docker
bundler_args: "--without development --deployment"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - git checkout -- .
  - bundle exec rake deploy

