images:
  - repository_uri: 980331077313.dkr.ecr.ap-northeast-1.amazonaws.com/capibara/app
    context: .
    docker_file: ./Dockerfile
    dependencies:
      - app/
      - config/
      - db/
      - lib/
      - public/
      - .dockerignore
      - docker-entrypoint.sh
      - Dockerfile
      - Gemfile
      - Gemfile.lock
  - repository_uri: 980331077313.dkr.ecr.ap-northeast-1.amazonaws.com/capibara/nginx
    context: nginx
    docker_file: ./nginx/Dockerfile
    dependencies:
      - nginx/
services:
  - cluster: capibara
    service: capibara-app
