default: &default
  adapter: redis
  url: redis://localhost:6379/1

development:
  <<: *default
  channel_prefix: capibara_development

test:
  <<: *default
  channel_prefix: capibara_test

production:
  <<: *default
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: capibara_production
